"""Constants for mock data used in assets."""

RAW_TRANSACTIONS_DATA = [
    {
        "transaction_id": "txn_001",
        "customer_id": "cust_01",
        "amount": 250.75,
        "date": "2024-01-15",
        "merchant": "Amazon",
    },
    {
        "transaction_id": "txn_002",
        "customer_id": "cust_02",
        "amount": 89.99,
        "date": "2024-01-15",
        "merchant": "Starbucks",
    },
    {
        "transaction_id": "txn_003",
        "customer_id": "cust_01",
        "amount": 1200.00,
        "date": "2024-01-16",
        "merchant": "Apple Store",
    },
    {
        "transaction_id": "txn_004",
        "customer_id": "cust_03",
        "amount": 45.50,
        "date": "2024-01-16",
        "merchant": "Gas Station",
    },
    {
        "transaction_id": "txn_005",
        "customer_id": "cust_02",
        "amount": 15.99,
        "date": "2024-01-17",
        "merchant": "Netflix",
    },
    {
        "transaction_id": "txn_006",
        "customer_id": "cust_04",
        "amount": 320.25,
        "date": "2024-01-17",
        "merchant": "Grocery Store",
    },
    {
        "transaction_id": "txn_007",
        "customer_id": "cust_01",
        "amount": 75.00,
        "date": "2024-01-18",
        "merchant": "Restaurant",
    },
    {
        "transaction_id": "txn_008",
        "customer_id": "cust_03",
        "amount": 199.99,
        "date": "2024-01-18",
        "merchant": "Best Buy",
    },
    {
        "transaction_id": "txn_009",
        "customer_id": "cust_05",
        "amount": 12.50,
        "date": "2024-01-19",
        "merchant": "Coffee Shop",
    },
    {
        "transaction_id": "txn_010",
        "customer_id": "cust_04",
        "amount": 450.00,
        "date": "2024-01-19",
        "merchant": "Hotel",
    },
]

RAW_CUSTOMERS_DATA = [
    {
        "customer_id": "cust_01",
        "name": "Alice Johnson",
        "email": "alice@email.com",
        "signup_date": "2023-06-15",
        "segment": "premium",
    },
    {
        "customer_id": "cust_02",
        "name": "Bob Smith",
        "email": "bob@email.com",
        "signup_date": "2023-08-22",
        "segment": "standard",
    },
    {
        "customer_id": "cust_03",
        "name": "Carol Davis",
        "email": "carol@email.com",
        "signup_date": "2023-09-10",
        "segment": "standard",
    },
    {
        "customer_id": "cust_04",
        "name": "David Wilson",
        "email": "david@email.com",
        "signup_date": "2023-11-03",
        "segment": "premium",
    },
    {
        "customer_id": "cust_05",
        "name": "Eva Brown",
        "email": "eva@email.com",
        "signup_date": "2024-01-08",
        "segment": "basic",
    },
]

RAW_ACCOUNTS_DATA = [
    {
        "account_id": "acc_001",
        "customer_id": "cust_01",
        "account_type": "checking",
        "balance": 2500.00,
        "created_date": "2023-06-16",
    },
    {
        "account_id": "acc_002",
        "customer_id": "cust_01",
        "account_type": "savings",
        "balance": 15000.00,
        "created_date": "2023-06-16",
    },
    {
        "account_id": "acc_003",
        "customer_id": "cust_02",
        "account_type": "checking",
        "balance": 1200.50,
        "created_date": "2023-08-23",
    },
    {
        "account_id": "acc_004",
        "customer_id": "cust_03",
        "account_type": "checking",
        "balance": 850.75,
        "created_date": "2023-09-11",
    },
    {
        "account_id": "acc_005",
        "customer_id": "cust_03",
        "account_type": "savings",
        "balance": 5500.00,
        "created_date": "2023-09-11",
    },
    {
        "account_id": "acc_006",
        "customer_id": "cust_04",
        "account_type": "checking",
        "balance": 3200.25,
        "created_date": "2023-11-04",
    },
    {
        "account_id": "acc_007",
        "customer_id": "cust_04",
        "account_type": "premium",
        "balance": 25000.00,
        "created_date": "2023-11-04",
    },
    {
        "account_id": "acc_008",
        "customer_id": "cust_05",
        "account_type": "checking",
        "balance": 450.00,
        "created_date": "2024-01-09",
    },
]

PREPARED_TRANSACTIONS_DATA = [
    {
        "transaction_id": "txn_001",
        "customer_id": "cust_01",
        "amount": 250.75,
        "date": "2024-01-15",
        "merchant": "Amazon",
        "category": "retail",
        "is_large_transaction": False,
    },
    {
        "transaction_id": "txn_002",
        "customer_id": "cust_02",
        "amount": 89.99,
        "date": "2024-01-15",
        "merchant": "Starbucks",
        "category": "food_beverage",
        "is_large_transaction": False,
    },
    {
        "transaction_id": "txn_003",
        "customer_id": "cust_01",
        "amount": 1200.00,
        "date": "2024-01-16",
        "merchant": "Apple Store",
        "category": "electronics",
        "is_large_transaction": True,
    },
    {
        "transaction_id": "txn_004",
        "customer_id": "cust_03",
        "amount": 45.50,
        "date": "2024-01-16",
        "merchant": "Gas Station",
        "category": "fuel",
        "is_large_transaction": False,
    },
    {
        "transaction_id": "txn_005",
        "customer_id": "cust_02",
        "amount": 15.99,
        "date": "2024-01-17",
        "merchant": "Netflix",
        "category": "entertainment",
        "is_large_transaction": False,
    },
    {
        "transaction_id": "txn_006",
        "customer_id": "cust_04",
        "amount": 320.25,
        "date": "2024-01-17",
        "merchant": "Grocery Store",
        "category": "food_beverage",
        "is_large_transaction": False,
    },
    {
        "transaction_id": "txn_007",
        "customer_id": "cust_01",
        "amount": 75.00,
        "date": "2024-01-18",
        "merchant": "Restaurant",
        "category": "food_beverage",
        "is_large_transaction": False,
    },
    {
        "transaction_id": "txn_008",
        "customer_id": "cust_03",
        "amount": 199.99,
        "date": "2024-01-18",
        "merchant": "Best Buy",
        "category": "electronics",
        "is_large_transaction": False,
    },
    {
        "transaction_id": "txn_009",
        "customer_id": "cust_05",
        "amount": 12.50,
        "date": "2024-01-19",
        "merchant": "Coffee Shop",
        "category": "food_beverage",
        "is_large_transaction": False,
    },
    {
        "transaction_id": "txn_010",
        "customer_id": "cust_04",
        "amount": 450.00,
        "date": "2024-01-19",
        "merchant": "Hotel",
        "category": "travel",
        "is_large_transaction": False,
    },
]

PREPARED_CUSTOMERS_DATA = [
    {
        "customer_id": "cust_01",
        "name": "Alice Johnson",
        "email": "alice@email.com",
        "signup_date": "2023-06-15",
        "segment": "premium",
        "days_since_signup": 587,
        "is_premium": True,
    },
    {
        "customer_id": "cust_02",
        "name": "Bob Smith",
        "email": "bob@email.com",
        "signup_date": "2023-08-22",
        "segment": "standard",
        "days_since_signup": 519,
        "is_premium": False,
    },
    {
        "customer_id": "cust_03",
        "name": "Carol Davis",
        "email": "carol@email.com",
        "signup_date": "2023-09-10",
        "segment": "standard",
        "days_since_signup": 500,
        "is_premium": False,
    },
    {
        "customer_id": "cust_04",
        "name": "David Wilson",
        "email": "david@email.com",
        "signup_date": "2023-11-03",
        "segment": "premium",
        "days_since_signup": 446,
        "is_premium": True,
    },
    {
        "customer_id": "cust_05",
        "name": "Eva Brown",
        "email": "eva@email.com",
        "signup_date": "2024-01-08",
        "segment": "basic",
        "days_since_signup": 380,
        "is_premium": False,
    },
]

PREPARED_ACCOUNTS_DATA = [
    {
        "account_id": "acc_001",
        "customer_id": "cust_01",
        "account_type": "checking",
        "balance": 2500.00,
        "created_date": "2023-06-16",
        "balance_tier": "medium",
        "days_active": 586,
    },
    {
        "account_id": "acc_002",
        "customer_id": "cust_01",
        "account_type": "savings",
        "balance": 15000.00,
        "created_date": "2023-06-16",
        "balance_tier": "high",
        "days_active": 586,
    },
    {
        "account_id": "acc_003",
        "customer_id": "cust_02",
        "account_type": "checking",
        "balance": 1200.50,
        "created_date": "2023-08-23",
        "balance_tier": "medium",
        "days_active": 518,
    },
    {
        "account_id": "acc_004",
        "customer_id": "cust_03",
        "account_type": "checking",
        "balance": 850.75,
        "created_date": "2023-09-11",
        "balance_tier": "low",
        "days_active": 499,
    },
    {
        "account_id": "acc_005",
        "customer_id": "cust_03",
        "account_type": "savings",
        "balance": 5500.00,
        "created_date": "2023-09-11",
        "balance_tier": "medium",
        "days_active": 499,
    },
    {
        "account_id": "acc_006",
        "customer_id": "cust_04",
        "account_type": "checking",
        "balance": 3200.25,
        "created_date": "2023-11-04",
        "balance_tier": "medium",
        "days_active": 445,
    },
    {
        "account_id": "acc_007",
        "customer_id": "cust_04",
        "account_type": "premium",
        "balance": 25000.00,
        "created_date": "2023-11-04",
        "balance_tier": "high",
        "days_active": 445,
    },
    {
        "account_id": "acc_008",
        "customer_id": "cust_05",
        "account_type": "checking",
        "balance": 450.00,
        "created_date": "2024-01-09",
        "balance_tier": "low",
        "days_active": 379,
    },
]

S3_PATHS = {
    "raw_transactions": "s3://acme-analytics/raw/transactions.csv",
    "raw_customers": "s3://acme-analytics/raw/customers.csv",
    "raw_accounts": "s3://acme-analytics/raw/accounts.csv",
    "prepared_transactions": "s3://acme-analytics/prepared/transactions.parquet",
    "prepared_customers": "s3://acme-analytics/prepared/customers.parquet",
    "prepared_accounts": "s3://acme-analytics/prepared/accounts.parquet",
}
